controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: true

    diff_cont:
      type:  diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_footprint

    left_wheel_names: ['left_drive_joint']
    right_wheel_names: ['right_drive_joint']
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  
    wheel_separation: 0.44
    wheel_radius: 0.06

    use_stamped_vel: false

    velocity_rolling_window_size: 10

    
    

   